### ISSUE TITLE
Build Failure on Device

### ISSUE THREAD

**Issue by mfgoalie** [sideshowcoder/jpgcompressor#2]
Hi, this works extremely well on the simulator, so I'm hoping to fix it on the local device. I've added:

<module platform="iphone" version="0.5.1">com.sideshowcoder.jpgcompressor</module>

to my tiapp.xml but continue to get this error when I try to build for testing on an iPhone 4 (iOS 5.0):

[ERROR] 
[ERROR] Error: Traceback (most recent call last):
  File "/Users/mfogg/Library/Application Support/Titanium/mobilesdk/osx/2.0.2.GA/iphone/builder.py", line 1465, in main
    execute_xcode("iphoneos%s" % iphone_version,args,False)
  File "/Users/mfogg/Library/Application Support/Titanium/mobilesdk/osx/2.0.2.GA/iphone/builder.py", line 1224, in execute_xcode
    output = run.run(args,False,False,o)
  File "/Users/mfogg/Library/Application Support/Titanium/mobilesdk/osx/2.0.2.GA/iphone/run.py", line 41, in run
    sys.exit(rc)
SystemExit: 65

The odd part is, when I erase that line from the tiapp.xml the project builds fine and installs on the phone correctly (although, obviously it complains that the module is missing). Any idea what the issue may be?

**Comment by sideshowcoder** [comment]
I think this should actually be fixed with the latest release :+1: it took forever but here we go :+1:
